# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PagecallEmbedTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PagecallEmbedTest
  pod 'PageCallSDK', '~> 2.2.0', :source => 'https://github.com/pplink/pagecall-specs.git'

end
