target 'PageCall' do
    use_frameworks!
    pod 'PageCallSDK', :source => "https://github.com/pplink/pagecall-specs.git"
    pod 'GoogleWebRTC', :source => "https://github.com/CocoaPods/Specs.git"
end
