# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PagecallWithSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PagecallWithSwiftUI
  pod 'PageCallSDK', '~> 2.2.0', :source => 'https://github.com/pplink/pagecall-specs.git'
  pod 'GoogleWebRTC'

end
